### PR TITLE
Add readResolve() to UnitActionType so the required static items are …

### PR DESCRIPTION
**Pull request by ThislsAUsername**
…used.

### CODE REVIEW

**Comment by ThatIsAUsername** [comment]
Pros: Also simple to implement, and guarantees that `==` will work even after save/load.
Cons: I don't think I see one, besides having to learn about `readResolve`, which is really a pro.

**Comment by ThislsAUsername** [comment]
> Pros: Also simple to implement, and guarantees that `==` will work even after save/load.
> Cons: I don't think I see one, besides having to learn about `readResolve`, which is really a pro.

Hah, yes.
I think I may try to fix the terrains to use this same sort of logic so I can simplify their serialization as well, and I think it may as well be on this PR.
Thoughts?

**Comment by ThatIsAUsername** [comment]
> I think I may try to fix the terrains to use this same sort of logic so I can simplify their serialization as well, and I think it may as well be on this PR.
Thoughts?

Sure, why not?

**Comment by ThislsAUsername** [comment]
> Sure, why not?

Because I'm busy reviewing your code? Heh.

**Comment by ThatIsAUsername** [comment]
> Because I'm busy reviewing your code? Heh.

Oh, cry to me.

**Comment by ThislsAUsername** [comment]
> Oh, cry to me.

I totally am. Life is *hard* when I have to review code instead of writing it ;v

**Comment by ThislsAUsername** [comment]
This is probably the next branch that should be merged.

**Pull request merged**
