### PR TITLE
Fix Max having amazing D2D inf

### PR DESCRIPTION
**Pull request by ThislsAUsername**
I didn't do an early out since "distance units" doesn't explicitly call out non-inf?
But also neither does his buff description?

I dunno.

### CODE REVIEW

**Comment by ThatIsAUsername** [comment]
> doesn't explicitly call out non-inf

Sort of. It says "Direct combat units have high firepower", but also clarifies "+50/0 vehicle direct combat".

> early out

You mean using `&&` instead of `||`? That would have left infs with a close-range buff.

**Comment by ThislsAUsername** [comment]
> Sort of. It says "Direct combat units have high firepower", but also clarifies "+50/0 vehicle direct combat".

The parenthetical is my more-precise addition. It is not the "canonical text".
> > early out
> 
> You mean using `&&` instead of `||`? That would have left infs with a close-range buff.

No, I mean checking for `TROOP` at the start, which would exclude them from consideration for the indirect debuff.

**Comment by ThatIsAUsername** [comment]
Gotcha, I think I'm tracking now. Yeah, neither explicitly mentions "non-infantry" units getting the buff, but in practice only non-infantry get the buff, and I guess there's room for interpretation on whether hypothetical future ranged infantry should get the debuff. I could go either way.

Looks good.

**Comment by ThatIsAUsername** [comment]
Simple 'nuff. Ship it.

**Pull request merged**
